version: '3.8'

# Shared volume mount configuration
x-storage-volumes: &storage-volumes
  - vault_storage:/vault-storage
  - vault_config:/vault-config

services:
  gateway:
    image: node:18
    working_dir: /app
    volumes:
      - ./gateway:/app
    command: sh -c "npm install && npm start"
    ports:
      - "8000:8000"
    networks:
      - nimbus_net

  auth-service:
    image: python:3.10
    working_dir: /app
    volumes:
      - ./auth-service:/app
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001"
    networks:
      - nimbus_net

  upload-service:
    image: python:3.10
    working_dir: /app
    volumes:
      - ./upload-service:/app
      <<: *storage-volumes  # Mount shared storage
    depends_on:
      storage-init:
        condition: service_completed_successfully
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8002"
    ports:
      - "8002:8002"
    networks:
      - nimbus_net

  storage-service:
    image: python:3.10
    working_dir: /app
    volumes:
      - ./storage-service:/app
      <<: *storage-volumes
    depends_on:
      storage-init:
        condition: service_completed_successfully
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8003"
    ports:
      - "8003:8003"
    networks:
      - nimbus_net

  metadata-service:
    image: python:3.10
    working_dir: /app
    volumes:
      - ./metadata-service:/app
      <<: *storage-volumes
    depends_on:
      storage-init:
        condition: service_completed_successfully
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8004"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: metadata
    ports:
      - "8004:8004"
    networks:
      - nimbus_net

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: metadata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nimbus_net

  admin-ui:
    image: node:18
    working_dir: /app
    volumes:
      - ./admin-ui:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    networks:
      - nimbus_net

  storage-init:
    build:
      context: .
      dockerfile: ./storage-init/Dockerfile
    volumes:
      - vault_storage:/vault-storage
    restart: "no"  # Run once only

networks:
  nimbus_net:
    driver: bridge

volumes:
  db_data:
  vault_storage:
    driver: local
  vault_config:
    driver: local

