version: '3.9'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - gateway
      - admin-ui

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - upload-service
      - metadata-service

  auth-service:
    build: ./auth-service
    environment:
      - PORT=8001
    ports:
      - "8001:8001"

  upload-service:
    build: ./upload-service
    environment:
      - PORT=8002
    ports:
      - "8002:8002"

  storage-service:
    build: ./storage-service
    environment:
      - PORT=8004
    ports:
      - "8004:8004"

  metadata-service:
    build: ./metadata-service
    environment:
      - PORT=8003
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
    ports:
      - "8003:8003"
    depends_on:
      - db

  admin-ui:
    build: ./admin-ui
    ports:
      - "3001:3000"  # Host:Container port mapping

  db:
    image: postgres:15
    env_file: ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  db_data:
