version: '3.9'
services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      auth-service:
        condition: service_healthy
      upload-service:
        condition: service_healthy
      metadata-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health/ready"]
      interval: 30s
      timeout: 5s
      retries: 3

  auth-service:
    build: ./auth-service
    environment:
      - PORT=8001
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health/ready"]
      interval: 30s
      timeout: 5s
      retries: 3

  upload-service:
    build: ./upload-service
    environment:
      - PORT=8002
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health/ready"]
      interval: 30s
      timeout: 5s
      retries: 3

  storage-service:
    build: ./storage-service
    environment:
      - PORT=8004
    ports:
      - "8004:8004"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health/ready"]
      interval: 30s
      timeout: 5s
      retries: 3

  metadata-service:
    build: ./metadata-service
    environment:
      - PORT=8003
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
    ports:
      - "8003:8003"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health/ready"]
      interval: 30s
      timeout: 5s
      retries: 3

  admin-ui:
    build: ./admin-ui
    ports:
      - "3001:3001"
    depends_on:
      gateway:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health/ready"]
      interval: 30s
      timeout: 5s
      retries: 3

  db:
    image: postgres:15
    env_file: ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  db_data:
